server:
  port: 8180

spring:
  application:
    name: sqr-equation
  datasource:
    url: jdbc:postgressql://localhost:5432/dbsqrequation?prepareThreshold=0
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    encoding: UTF-8
    sql-migration-prefix: prod
    schemas: public
    locations: classpath:db/migration/postgres
    validate-on-migrate: true
